load("@rules_python//python:defs.bzl", "py_library")

package(default_visibility = ["//python/com/yanicksenn/templating:__subpackages__"])

py_library(
    name = "rules",
    srcs = glob(["*.py"]),
)
