load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "shared",
    srcs = ["shared.go"],
    importpath = "github.com/yanicksenn/its-almost-like-at-google/go/com/yanicksenn/taste/shared",
    visibility = ["//visibility:public"],
)
