load("@rules_java//java:defs.bzl", "java_library")

package(default_visibility = ["//visibility:public"])

java_library(
    name = "numbers",
    srcs = glob(["*.java"]),
    deps = [
        "//java/com/yanicksenn/functions"
    ]
)