load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "taste_parser",
    srcs = ["parser.go"],
    importpath = "github.com/yanicksenn/its-almost-like-at-google/go/com/yanicksenn/taste/taste_parser",
    deps = [
        "//go/com/yanicksenn/taste/shared"
    ],
    visibility = ["//visibility:public"],
)
