load("@rules_python//python:defs.bzl", "py_library")

package(default_visibility = ["//visibility:public"])

py_library(
    # TODO - yanicksenn: Rename flags to flags-lib for consistency.
    name = "flags",
    srcs = ["flags.py"]
)
