sh_binary(
    name = "todos",
    srcs = ["search_todos.sh"],
    data = [
        "//python/com/yanicksenn/search/todos:todos",
    ],
    deps = [
        "@bazel_tools//tools/bash/runfiles",
    ],
)
