load("@rules_java//java:defs.bzl", "java_test")

# java_test(
#     name = "CalendarTest",
#     srcs = ["CalendarTest.java"],
#     deps = [
#         "//java/com/yanicksenn/games/vaultmanager:vaultmanager-java-proto",
#         "//java/com/yanicksenn/games/vaultmanager:vaultmanager-lib",
#         "@maven//:com_google_truth_truth",
#         "@maven//:junit_junit",
#         "@maven//:pl_pragmatists_JUnitParams",
#         "@protobuf//java/core",
#     ],
# )
#
# java_test(
#     name = "CalendarLeapYearTest",
#     srcs = ["CalendarLeapYearTest.java"],
#     deps = [
#         "//java/com/yanicksenn/games/vaultmanager:vaultmanager-java-proto",
#         "//java/com/yanicksenn/games/vaultmanager:vaultmanager-lib",
#         "@maven//:com_google_truth_truth",
#         "@maven//:junit_junit",
#         "@maven//:pl_pragmatists_JUnitParams",
#         "@protobuf//java/core",
#     ],
# )
#
# java_test(
#     name = "CalendarValidationTest",
#     srcs = ["CalendarValidationTest.java"],
#     deps = [
#         "//java/com/yanicksenn/games/vaultmanager:vaultmanager-java-proto",
#         "//java/com/yanicksenn/games/vaultmanager:vaultmanager-lib",
#         "@maven//:com_google_truth_truth",
#         "@maven//:junit_junit",
#         "@maven//:pl_pragmatists_JUnitParams",
#         "@protobuf//java/core",
#     ],
# )
#
# test_suite(
#     name = "tests",
#     tests = [
#         ":CalendarTest",
#         ":CalendarLeapYearTest",
#         ":CalendarValidationTest",
#     ],
# )
